# Generated by Django 4.2.17 on 2025-08-13 08:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('employment-law', 'Employment Law'), ('property-law', 'Property Law'), ('business-law', 'Business Law'), ('family-law', 'Family Law'), ('estate-law', 'Estate Law'), ('general', 'General'), ('consumer-law', 'Consumer Law')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], max_length=10)),
                ('description', models.TextField()),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('author', models.CharField(max_length=100)),
                ('preview', models.BooleanField(default=True)),
                ('price', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-downloads', '-rating', '-created_at'],
            },
        ),
    ]
